# Generated by Django 2.1.2 on 2019-04-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationtask',
            old_name='execute',
            new_name='read',
        ),
        migrations.AddField(
            model_name='calculationtask',
            name='result',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calculationtask',
            name='status',
            field=models.CharField(choices=[('Created', '已创建'), ('Executing', '执行中'), ('Completed', '已完成')], default='Created', max_length=20, verbose_name='状态'),
        ),
    ]
